let son = prompt("Ismingizni kiriting")
let son1 = prompt("Familiyangizni kiriting")
let son2 = prompt("Yoshingizni kiriting")
let son3 = prompt("Tumaningizni kiriting")
let son4 = prompt("Yoqtirgan faningizni kiriting")
console.log(`Ismi: ${son}`)
console.log(`Familiyasi: ${son1}`)
console.log(`Yoshi: ${son2}`)
console.log(`Tumani: ${son3}`)
console.log(`Yoqtirgan fani: ${son4}`)